### PR TITLE
odb: dbMarker

### PR DESCRIPTION
**Pull request by gadfort**
Adds:
- `dbMarker`, `dbMarkerCategory`, `dbMarkerGroup` to support tracking of markers in database
- `Line` as a geom type (this has come up a few times now, so it was easier to add a class).

Changes:
- PDN, PSM, GRT to use `dbMarker`
- moved parsing of report information from `DRCWidget` to `dbMarkerGroup`
- Updates `DRCWidget` to handle switching between marker information.

Discussion:
- currently getting DRC information into images for SiliconCompiler and ORFS rely on reading the drc report back in, which is not needed anymore, but also is also not working at the moment and needs to be reworked how to do this (ie. select the DRC datasource).
- Should be database provide callbacks for the GUI to be able to automatically update the `DRCWidget` or should we just rely on manually updating the list?
- DRT breaks the connection between odb objects and DRT objects so obstruction information is lost at the moment, therefore that implementation is not included for now (I can include it if the loss of this information is acceptable, but I don't think it would be a good idea until the losses can be avoided).
- The JSON file format is a little more descriptive for reporting (compared to the TR file), but there isn't a "spec" for this file, so I did my best to handle it, but we can discuss what makes sense for this file.
- The DRC widget is also tracking if a marker has been viewed or is visible (it might make sense to move the viewed/visited into the database? and the visibility can continue to be handled in the GUI.

### CODE REVIEW

**Comment by gadfort** [comment]
@maliberty marking this draft until discussions points are resolved.

**Comment by maliberty** [comment]
I don't follow the bit about drt and "obstruction information".   Please elaborate.

File: src/grt/src/fastroute/src/utility.cpp [hunk 1]
```diff
@@ -964,7 +964,7 @@ void FastRouteCore::layerAssignmentV4()
         treenodes[n2a].assigned = true;
 
       }  // edge len > 0
-    }    // eunmerating edges
+    }  // eunmerating edges
```
Comment (maliberty) [inline src/grt/src/fastroute/src/utility.cpp:967]: These whitespace changes seem unrelated.

File: src/odb/src/codeGenerator/schema.json [hunk 2]
```diff
@@ -311,6 +311,19 @@
...
+      "second":"dbMarkerCategory",
+      "type":"1_n",
+      "tbl_name":"categories_tbl_",
+      "hash":true
+    },
+    {
+      "first":"dbMarkerCategory",
+      "second":"dbMarker",
+      "type":"1_n",
+      "tbl_name":"marker_tbl_"
```
Comment (maliberty) [inline src/odb/src/codeGenerator/schema.json:326]: This creates a two-level hierarchy.  In KLayout they made categories able to contain other categories to allow for arbitrary depth.  I think that is more flexible.

File: src/odb/src/db/dbBlock.cpp [hunk 3]
```diff
@@ -4258,4 +4281,26 @@ dbTech* dbBlock::getTech()
...
+  return dbSet<dbMarkerGroup>(block, block->_marker_group_tbl);
+}
+
+dbMarkerGroup* dbBlock::findMarkerGroup(const char* name)
+{
+  _dbBlock* block = (_dbBlock*) this;
+  return (dbMarkerGroup*)block->_marker_group_hash.find(name);
+}
+
+void dbBlock::writeMarkerGroups(const std::string& file)
```
Comment (maliberty) [inline src/odb/src/db/dbBlock.cpp:4296]: @QuantamHD will want to have

void dbBlock::writeMarkerGroups(const std::string& file)
void dbBlock::writeMarkerGroups(const std::ostream& file)

Where the former calls the later.

File: src/gui/src/drcWidget.cpp [hunk 4]
```diff
@@ -56,55 +51,10 @@ namespace gui {
...
-      for (const auto& pt : *s) {
-        outline << QPoint(pt.x(), pt.y());
-      }
-    }
-  }
-
-  QRect bounds = outline.boundingRect();
-  bbox_
-      = odb::Rect(bounds.left(), bounds.bottom(), bounds.right(), bounds.top());
+DRCViolation::DRCViolation(const std::string& name, odb::dbMarker* marker)
```
Comment (maliberty) [inline src/gui/src/drcWidget.cpp:54]: Should the name be part of the marker?

File: src/gui/src/drcWidget.cpp [hunk 5]
```diff
@@ -117,15 +67,18 @@ void DRCViolation::paint(Painter& painter)
...
+        const odb::Point pt = std::get<odb::Point>(shape);
+        painter.drawX(pt.x(), pt.y(), min_box);
+      } else if (std::holds_alternative<odb::Line>(shape)) {
+        const odb::Line line = std::get<odb::Line>(shape);
+        painter.drawLine(line.pt0(), line.pt1());
+      } else if (std::holds_alternative<odb::Rect>(shape)) {
+        painter.drawRect(std::get<odb::Rect>(shape));
+      } else {
+        painter.drawPolygon(std::get<odb::Polygon>(shape));
+        ;
```
Comment (maliberty) [inline src/gui/src/drcWidget.cpp:81]: rm stray ;

**Review by maliberty — CHANGES_REQUESTED** [review]

**Comment by maliberty** [comment]
If you load a drc file can you assign it to a group?  For loading drcs from an external tool it would be helpful to put them in a specific category.

File: src/grt/src/fastroute/src/utility.cpp (hunk 1 above)
Comment (gadfort) [reply src/grt/src/fastroute/src/utility.cpp:967]: this is probably form the clang-format version issue I mentioned. I'll need to redo the formatting on an older version than what is currently installed.

File: src/odb/src/db/dbBlock.cpp (hunk 3 above)
Comment (QuantamHD) [reply src/odb/src/db/dbBlock.cpp:4296]: ❤️

**Comment by gadfort** [comment]
@maliberty The file IO still needs to be fixed, but I was able to remove the group and just have recursive categories.

File: src/odb/src/db/dbMarkerCategory.cpp [hunk 6]
```diff
@@ -0,0 +1,1037 @@
...
+// POSSIBILITY OF SUCH DAMAGE.
+
+// Generator Code Begin Cpp
+#include "dbMarkerCategory.h"
+
+#include "dbBlock.h"
+#include "dbDatabase.h"
+#include "dbDiff.hpp"
+#include "dbMarker.h"
+#include "dbMarkerCategory.h"
```
[the remark this answers is not in the document]
Comment (gadfort) [reply src/odb/src/db/dbMarkerCategory.cpp:40]: this is getting emitted by the code generator

[the remark this answers is not in the document]
Comment (maliberty) [reply src/odb/src/db/dbMarkerCategory.cpp:40]: Fixable with
```
--- a/src/odb/src/codeGenerator/gen.py
+++ b/src/odb/src/codeGenerator/gen.py
@@ -135,9 +135,10 @@ for relation in schema["relations"]:
         inParentField["schema"] = relation["schema"]
 
     schema["classes"][parent]["fields"].append(inParentField)
-    schema["classes"][parent]["cpp_includes"].extend(
-        [f"{relation['second']}.h", "odb/dbSet.h"]
-    )
+    if relation["first"] != relation['second']:
+        schema["classes"][parent]["cpp_includes"].extend(
+            [f"{relation['second']}.h", "odb/dbSet.h"]
+        )
```

**Comment by maliberty** [comment]
@gadfort where does this stand with respect to being ready for review/merge?

**Comment by gadfort** [comment]
@maliberty I think it's ready, it contains what we discussed the other week.

File: src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+    },
+    {
+      "name":"source_",
+      "type":"std::string",
+      "flags":["no-get"]
+    },
+    {
+      "name": "max_markers_",
+      "type": "int",
+      "default": "10000"
```
Comment (maliberty) [inline src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json:23]: What is the purpose of this?

File: src/odb/include/odb/db.h [hunk 8]
```diff
@@ -7878,6 +7896,114 @@ class dbLogicPort : public dbObject
...
+                     std::ifstream& report);
+
+  static dbMarkerCategory* create(dbBlock* block, const char* name);
+  static dbMarkerCategory* createOrReplace(dbBlock* block, const char* name);
+  static dbMarkerCategory* createOrGet(dbBlock* block, const char* name);
+  static dbMarkerCategory* create(dbMarkerCategory* category, const char* name);
+  static dbMarkerCategory* createOrGet(dbMarkerCategory* category,
+                                       const char* name);
+  static dbMarkerCategory* createOrReplace(dbMarkerCategory* category,
+                                           const char* name);
```
Comment (maliberty) [inline src/odb/include/odb/db.h:8001]: This is different from most other classes.  As we have find & destroy, do we need all these others?

File: src/odb/include/odb/db.h [hunk 9]
```diff
@@ -7878,6 +7896,114 @@ class dbLogicPort : public dbObject
...
+
+  std::string getDescription() const;
+
+  void setSource(const std::string& source);
+
+  void setMaxMarkers(int max_markers);
+
+  int getMaxMarkers() const;
+
+  dbSet<dbMarker> getMarkers() const;
```
Comment (maliberty) [inline src/odb/include/odb/db.h:7961]: Can categories contain both markers and other categories?  Is this recursive?

File: src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json (hunk 7 above)
Comment (gadfort) [reply src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json:23]: to provide a mechanism to limit the number of markers that can get created. I suppose the default could be unlimited and then allow the tools to place an upper bound. (It was an attempt to have something standard across the different tools).

File: src/odb/include/odb/db.h (hunk 8 above)
Comment (gadfort) [reply src/odb/include/odb/db.h:8001]: technically we dont. The basic pattern create or get current shows up a lot (I could also just allow create to return the current one if it's found.
We don't need them, but they are somewhat helpful (`createorget` mainly)

File: src/odb/include/odb/db.h (hunk 9 above)
Comment (gadfort) [reply src/odb/include/odb/db.h:7961]: recursive and yeah can have both markers and categories. I decided it wasn't worth being pedantic about this and we should just allow the tools to do what makes sense in their case.

File: src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json (hunk 7 above)
Comment (maliberty) [reply src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json:23]: Is there any user control or support for it in the tools or is it for future use?

**Comment by maliberty** [comment]
Conflict to resolve...

File: src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json (hunk 7 above)
Comment (gadfort) [reply src/odb/src/codeGenerator/schema/chip/dbMarkerCategory.json:23]: The category stops creating dbMarkers when the limit is reached. So the enforcement is in odb. Each tool is already checking if the marker returned from `dbMarker::create` is a nullptr before populating it with information.

**Comment by gadfort** [comment]
@maliberty conflict resolved. I added a waived field to mirror what klayout has

**Review by maliberty — APPROVED** [review]

**Comment by stefanottili** [comment]
4 compile errors on MacOS Sequoia M1

OpenROAD-flow-scripts/tools/OpenROAD/src/odb/src/db/dbMarker.cpp:177:10: error: invalid operands to binary expression ('dbIStream' and 'std::size_t' (aka 'unsigned long'))
  177 |   stream >> item_count;
      |   ~~~~~~ ^  ~~~~~~~~~~
OpenROAD-flow-scripts/tools/OpenROAD/src/odb/include/odb/dbTypes.h:147:12: note: candidate function not viable: no known conversion from 'std::size_t' (aka 'unsigned long') to 'dbGDSSTrans &' for 2nd argument
  147 | dbIStream& operator>>(dbIStream& stream, dbGDSSTrans& t);
      |            ^                             ~~~~~~~~~~~~~~
OpenROAD-flow-scripts/tools/OpenROAD/src/odb/src/db/dbMarker.cpp:236:10: error: use of overloaded operator '<<' is ambiguous (with operand types 'dbOStream' and 'size_type' (aka 'unsigned long'))
  236 |   stream << obj.sources_.size();
      |   ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
OpenROAD-flow-scripts/tools/OpenROAD/src/odb/include/odb/dbStream.h:86:14: note: candidate function
   86 |   dbOStream& operator<<(bool c)
      |              ^
OpenROAD-flow-scripts/tools/OpenROAD/src/odb/src/db/dbMarker.cpp:243:10: error: use of overloaded operator '<<' is ambiguous (with operand types 'dbOStream' and 'size_type' (aka 'unsigned long'))
  243 |   stream << obj.shapes_.size();
      |   ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
OpenROAD-flow-scripts/tools/OpenROAD/src/odb/include/odb/dbStream.h:86:14: note: candidate function
   86 |   dbOStream& operator<<(bool c)
      |              ^
4 errors generated.

**Comment by maliberty** [comment]
Its hard to see how dbGDSSTrans  relates to this PR.  Did it work on master prior to this merge?

**Comment by stefanottili** [comment]
OR compiled just fine last night ...

**Comment by gadfort** [comment]
@maliberty who is fixing this? I cannot compile on a Mac, but I could make some changes later today, but without a mac in the loop it would be impossible to ensure the changes cover everything

**Comment by stefanottili** [comment]
git bisect points to this and I'm willing and able to test ...

fe52a377858ba3e5e7125fd3d73dea36cb5e4281 is the first bad commit
commit fe52a377858ba3e5e7125fd3d73dea36cb5e4281
Author: Peter Gadfort <peter.gadfort@gmail.com>
Date:   Sun Oct 6 11:18:15 2024 -0400

    odb: add dbMarkerGroup/Category and markers
    
    Signed-off-by: Peter Gadfort <peter.gadfort@gmail.com>

**Comment by maliberty** [comment]
I have no mac either.  I would just make a branch with a best guess and ask @stefanottili to test it.  I can try if you want.

**Comment by gadfort** [comment]
@stefanottili  can you try: https://github.com/gadfort/OpenROAD/tree/casting

**Comment by stefanottili** [comment]
this compiles
```
@@ -173,7 +173,7 @@ dbIStream& operator>>(dbIStream& stream, _dbMarker& obj)
   stream >> obj.line_number_;
   // User Code Begin >>
   // handle shapes
-  std::size_t item_count;
+  int item_count;
   stream >> item_count;
   for (std::size_t i = 0; i < item_count; i++) {
     std::string db_type;
@@ -233,14 +233,14 @@ dbOStream& operator<<(dbOStream& stream, const _dbMarker& obj)
   stream << obj.line_number_;
   // User Code Begin <<
   // handle sources
-  stream << obj.sources_.size();
+  stream << static_cast<int>(obj.sources_.size());
   for (const auto& [db_type, dbid] : obj.sources_) {
     stream << std::string(dbObject::getTypeName(db_type));
     stream << dbid;
   }
 
   // handle shapes
-  stream << obj.shapes_.size();
+  stream << static_cast<int>(obj.shapes_.size());
   for (const dbMarker::MarkerShape& shape : obj.shapes_) {
     if (std::holds_alternative<Point>(shape)) {
       stream << _dbMarker::ShapeType::Point;
```
