### ISSUE TITLE
in boost 1.87 io_service has been removed, use io_context instead

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#6373]
### Describe the bug

Mac M1: `brew upgrade` upgraded boost from 1.86 to 1.87, now the compile fails with:
```
OpenROAD/src/dst/src/WorkerConnection.h:46:26: error: no type named 'io_service' in namespace 'boost::asio'
   46 |   WorkerConnection(asio::io_service& io_service,
      |                    ~~~~~~^
```
googling found this:
```
boost 1.87:

io_service was deprecated in favor of io_context back in 1.66.0 
(https://github.com/boostorg/asio/commit/b60e92b13ef68dfbb9af180d76eae41d22e19356).
Easiest approach is to require a minimum of Boost 1.66.0 and use newer APIs.
Otherwise, would need to create many #if BOOST_VERSION ... conditions for compatibility.
```

### Expected Behavior

compile using boost 1.87

### Environment

```shell
M1 Mac homebrew
```

### To Reproduce

build using boost 1.87

**Comment by stefanottili** [comment]
I found that boost unlink/link allows cmake to find and use an older boost version.
brew unlink boost@1.87
brew link boost@1.85
