### ISSUE TITLE
MacOS: brew upgrade installed swig 4.4.0 broke the OR compile

### ISSUE THREAD

**Issue by stefanottili** [The-OpenROAD-Project/OpenROAD#8769]
### Describe the bug

macOS Tahoe, using homebrew for dependencies: as of Oct 30 2025, `brew upgrade` installs `SWIG Version 4.4.0`
```
build/src/dbSta/src/CMakeFiles/dbSta.dir/dbStaTCL_wrap.cxx:7859:7: error: use of undeclared identifier '$function'; did you mean 'boost_swap_impl::function'?
 7859 |       $function 
      |       ^~~~~~~~~
      |       boost_swap_impl::function
```
using swig 4.3.0 on wsl ubuntu 22, `$function` get's replaced with `set_delay_calculator_cmd((char const *)arg1);`

### Expected Behavior

compile using `SWIG Version 4.4.0`

### Environment

```shell
macOS Tahoe, homebrew, swig 4.4.0
```

### To Reproduce

use swig 4.4.0

### Relevant log output

```shell

```

### Additional Context
```
 7849 #ifdef __cplusplus
 7850 extern "C" {
 7851 #endif  
 7852 SWIGINTERN int
 7853 _wrap_delay_calc_names(ClientData clientData SWIGUNUSED, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
 7854   StringSeq result;
 7855       
 7856   if (SWIG_GetArgs(interp, objc, objv,":sta::delay_calc_names ") == TCL_ERROR) SWIG_fail;
 7857   { 
 7858     try {
 7859       $function
 7860     }
 7861     catch (std::bad_alloc &) {
 7862       fprintf(stderr, "Error: out of memory.");
 7863       abort();
 7864     }
```

**Comment by maliberty** [comment]
@sombraSoft please update swig to 4.4 and let me know if you have issues with building OR.

**Comment by stefanottili** [comment]
Any update ?

**Comment by stefanottili** [comment]
In order to compile on MacOS with homebrew swig 4.4.1, the fix in https://github.com/The-OpenROAD-Project/OpenROAD/pull/9229 is not sufficient.
src/sta/tcl/Exception.i  needs to updated too.

**Comment by stefanottili** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/9231 fixed sta/tcl/Exception.i

**Comment by stefanottili** [comment]
I jumped the gun, https://github.com/The-OpenROAD-Project/OpenROAD/pull/9270 will fix this
